/* Generated by Together */

#include "Friend.h"
#include "GroupServerApp.h"

const cChar*	gc_standard_group=(const cChar*)RES_STRING(GP_FRIEND_H_00001);

long Friend::GetInvitedMax()
{
	return g_gpsvr->const_frnd.InvitedMax;
}
void Friend::InvitedCheck(Invited	*invited)
{
	FrndInvitedCheck(invited);
}
