/* Generated by Together */

#include "GuildMember.h"
#include "Guild.h"

bool GuildMember::JoinGuild(Guild *gld)
{
	return _BeginRun(gld)?true:false;
}
bool GuildMember::LeaveGuild()
{
	return _EndRun()?true:false;
}
Guild	*	GuildMember::GetGuild()
{
	return static_cast<Guild *>(GetChain());
}
