/* Generated by Together */

#ifndef GUILDMEMBER_H
#define GUILDMEMBER_H
#include "RunBiDirectChain.h"
#include "Invitation.h"
_DBC_USING
class	Guild;

class GuildMember: public RunBiDirectItem<GuildMember>
{
public:
	bool JoinGuild(Guild *gld);
	bool LeaveGuild();
	Guild	*	GetGuild();
};
#endif //GUILDMEMBER_H
