/* Generated by Together */

#ifndef GUILD_H
#define GUILD_H
#include "PreAlloc.h"
#include "RunBiDirectChain.h"
#include "GuildMember.h"
_DBC_USING
class	Player;

/**
 * @alias 行会 
 */
class Guild :public PreAllocStru , public RunBiDirectItem<Guild>, public RunBiDirectChain<GuildMember>
{
public:
	Guild(uLong size);
	void	Free(){PreAllocStru::Free();}
	static	Guild *Alloc();
	bool	BeginRun();
	bool	EndRun();
	Player *FindGuildMemByChaID(uLong id);

	uLong			m_id;
	char			m_name[17];				//行会名称
	char			m_motto[51];			//公会座右铭
	char			m_type;					//emGldTypeNavy-海军；emGldTypePirate-海盗
	BitMaskStatus	m_stat;					//0x0-正常;0x1-会费不足;0x2-成员数不足;0x4-会长声望不足
	uLong			m_remain_minute;		//公会解散剩余分钟数
	uLong			m_tick;
	uLong			m_leaderID;

	int				m_level;
	int				m_point;
	int				m_exp;

	/**
	 * @label 会长 
	 */
	Player	*	m_leader;					//会长，不允许变化
private:
	~Guild();

	void Initially();
	void Finally();

};
class ChkGuild: public Timer
{
public:
	ChkGuild(uLong interval):Timer(interval){}
private:
	void Process();
};

#endif //GUILD_H
