/* Generated by Together */

#include "Master.h"
#include "GroupServerApp.h"

long Master::GetInvitedMax()
{
	return g_gpsvr->const_master.InvitedMax;
}
void Master::InvitedCheck(Invited	*invited)
{
	MasterInvitedCheck(invited);
}
